### ISSUE TITLE
Should packages be unlisted?

### ISSUE THREAD

**Issue by gep13** [tpodolak/Cake.Intellisense#24]
I was just wondering if you felt it might be worth unlisting the Cake.IntellisenseGenerator related packages that you have pushed to NuGet.org, now that we have shipped Cake.Bakery, and intellisense support is now provided via OmniSharp?

Is there anything that your implementation provides that isn't provided already?

Would love to discuss this further. Thanks.

**Comment by tpodolak** [comment]
Hi, sorry for a super late response. I've just unlisted all of the packages.

Regards

**Comment by gep13** [comment]
Thank you very much for doing this! 👍
